stages:
  - build_and_test

image: "registry.esss.lu.se/ecdc/ess-dmsc/docker-centos7-build-node:12.3.0"

build_and_test:
  stage: build_and_test
  tags:
    - dc-zone
    - docker
  script:
    - echo "Running dependencies stage"
    - source /opt/rh/rh-python38/enable
    - python3.8 --version
    - python3.8 -m pip install --user --upgrade pip
    - python3.8 -m pip install --user -r requirements-dev.txt
    - echo "Checking Formatting..."
    - python3.8 -m black --check .
    - echo "Checking Static Analysis..."
    - python3.8 -m flake8
    - echo "Running tests"
    - python3.8 -m pytest --cov --cov-report=html --cov-report=term .
    - tar czf htmlcov.tar.gz htmlcov
  artifacts:
    paths:
      - htmlcov.tar.gz